### ISSUE TITLE
Support yaml meta & project files

### ISSUE THREAD

**Issue by Weldify** [Iron-Stag-Games/Lync#33]
I'd like meta and project files to support yaml too. Json is too verbose and strict.

Example json meta file
```json
{
	"properties": {
		"RunContext": "Server"
	}
}
```

Example yaml meta file:
```yaml
properties:
  RunContext: Server
```

**Comment by hoontee** [comment]
Roblox doesn't have a native way to parse YAML files. I do still think this is a good idea so I will investigate solutions.

**Comment by hoontee** [comment]
Was easier than I thought! Please update to [Alpha 22+](https://github.com/Iron-Stag-Games/Lync/releases) or [enable automatic updates](https://github.com/Iron-Stag-Games/Lync#configuration).
