### ISSUE TITLE
Support embedding luau code into YAML files

### ISSUE THREAD

**Issue by Weldify** [Iron-Stag-Games/Lync#36]
Yaml files are neat, but currently you can't define any roblox types or instance paths.
I propose a syntax that lets you embed some luau code into yaml:
```
myVec: @"Vector3.new(1, 2, 3)"
```

Anything inside `@""` is synced as luau code.
To use the `@` character itself, you should be able to do `@@` - this wont count as embed syntax and instead will just result in a `@` character.

**Comment by hoontee** [comment]
This is tricky and inconvenient to implement, so for now, consider instead using modules that return a single table. You will be able to use all Roblox classes and type checking.
