### ISSUE TITLE
`RBXM` files do not expand in the sourcemap

### ISSUE THREAD

**Issue by Weldify** [Iron-Stag-Games/Lync#40]
I have a couple of remote events but the sourcemap thinks they're instances:
![изображение](https://github.com/Iron-Stag-Games/Lync/assets/66477673/cd30c6ca-b3d8-4aba-92e7-ecf1c3e23d69)
![изображение](https://github.com/Iron-Stag-Games/Lync/assets/66477673/ea6f2077-a491-4475-9888-ad2e419054ac)

**Comment by hoontee** [comment]
This is a limitation of Lync. RBXMs cannot be read, so their classname in the sourcemap must be generic.

I can see that this particular class will cause type errors. Have you considering using a `*.Model.JSON` instead of an `RBXM` for these remotes?

**Comment by hoontee** [comment]
Will patch to read RBXMX contents. RBXM reading may not arrive until the Beta.

**Comment by hoontee** [comment]
`*.Model.JSON` and `RBXMX` files now expand in the sourcemap. `RBXM` files will not expand for a while ([PR appreciated!](https://github.com/Iron-Stag-Games/Lync/blob/main/Lync/sourcemap/rbxm.js))

Please update to [Alpha 22.4+](https://github.com/Iron-Stag-Games/Lync/releases) or [enable automatic updates](https://github.com/Iron-Stag-Games/Lync#configuration).

**Comment by hoontee** [comment]
Labeling this as a discussion. Should RBXMs expand in the sourcemap, or should we save CPU and only expand RBXMXs which users can use intentionally if they need them to be in the sourcemap?

**Comment by hoontee** [comment]
`RBXM` files now expand in the sourcemap.

Please update to [Alpha 22.6+](https://github.com/Iron-Stag-Games/Lync/releases) or [enable automatic updates](https://github.com/Iron-Stag-Games/Lync#configuration).
