### ISSUE TITLE
Don't require base during SERVE and FETCH

### ISSUE THREAD

**Issue by Weldify** [Iron-Stag-Games/Lync#54]
Currently if you try to SERVE or FETCH without "base" present in your `project.json`, you will get the following error:
![image](https://github.com/Iron-Stag-Games/Lync/assets/66477673/cd3715e5-da23-4a36-aba0-a2338fddf5a6)

"base" is required even though it is unused during SERVE and FETCH. It would be nice if "base" was optional in these cases.

**Comment by hoontee** [comment]
Fixed! Please update to [Alpha 24.1+](https://github.com/Iron-Stag-Games/Lync/releases) or [enable automatic updates](https://github.com/Iron-Stag-Games/Lync#usage).
