### ISSUE TITLE
Saving an edited instance should open the proper path

### ISSUE THREAD

**Issue by Weldify** [Iron-Stag-Games/Lync#59]
Currently, if you edit a synced model in studio and try to save it back into your file system, the file explorer prompt will open basically wherever. It would be very nice if it opened the explorer prompt where the model is actually located

**Comment by hoontee** [comment]
This is a limitation of [PromptSaveSelection](https://create.roblox.com/docs/reference/engine/classes/Plugin#PromptSaveSelection). I can't specify a path, just a name.
