### ISSUE TITLE
JSON Models don't properly set the class name in the sourcemap

### ISSUE THREAD

**Issue by silly-spongus** [Iron-Stag-Games/Lync#78]
I've specified a classname in my .model.json file, but when i build, the sourcemap it generates has the classname field set to "`Folder`". It also leaves this empty field named "ClassName"

Sourcemap:
![igAp9rn](https://github.com/user-attachments/assets/415507a7-a925-4d2a-a069-dfca7e64e079)
JSON Model:
![ZTvgKmA](https://github.com/user-attachments/assets/63555215-5eed-4b29-a7b0-31f6130a1bdf)

**Comment by hoontee** [comment]
Fixed! Please update to [Alpha 0.24.6](https://github.com/Iron-Stag-Games/Lync/releases) or [enable automatic updates](https://github.com/Iron-Stag-Games/Lync#usage).
