### ISSUE TITLE
Package updates/deletions do not replicate as expected

### ISSUE THREAD

**Issue by Pluviolithic** [Iron-Stag-Games/Lync#9]
To test this, simply setup a new project with a standard default.project.json with a packages folder defined:
```json
"ServerScriptService": {
  "Server": {
    "$clearOnSync": true,
    "$path": "src/server",
    "lib": {
      "$className": "Folder",
      "$path": "./ServerPackages"
    }
  }
},
```
Install a few wally packages to that folder. Some examples you might want to use:
```toml
[server-dependencies]
Cmdr = "evaera/cmdr@1.9.0"
ProfileService = "grilme99/profileservice@1.0.0"
```

Sync to a baseplate and do one of the following:
* Delete `lib`
* Delete entry from`wally.toml` and run `wally install`
* Change entry in `wally.toml` and run `wally install`
* Add entry to `wally.toml` and run `wally install`

In the cases that involved changing installed libraries, none of the changes replicate if they occur while sync is active. Pausing the plugin, resuming the plugin, or restarting the `Win_Sync.bat` script do not cause the changes to replicate. Studio has to be restarted.

Deleting `lib` in Roblox Studio permanently removes it until Studio is restarted, even if the listed pause/resume/restart steps listed above for the previous test are attempted.

**Comment by hoontee** [comment]
Behavior may have been improved, will need to do some testing on my end.
